apiVersion: v1
kind: Service
data:
  mapUsers: |
      - userarn: arn:aws:iam::063684395745:user/lakshmi
        username: admin
        groups:
          - system:masters
metadata:
  name: capstone-cluster
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: capstone
    type: sample_app
