apiVersion: v1
kind: Service
metadata:
  name: capstone-cluster
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: capstone
    type: sample_app
